language: python

branches:
  only:
    - master

sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -Uv pip setuptools wheel
  - pip install -r requirements_dev.txt
  - pip install .

script:
  - nosetests -v
  - pysamstats --type coverage fixture/test.bam > coverage.txt
  - pysamstats --type coverage --output=coverage.txt fixture/test.bam
  - pysamstats --type coverage --output=coverage.h5 --format=hdf5 fixture/test.bam
  - pysamstats --type coverage_binned --fasta=fixture/ref.fa fixture/test.bam > coverage_binned.txt
  - pysamstats --type coverage_binned --fasta=fixture/ref.fa --output=coverage_binned.txt fixture/test.bam
  - pysamstats --type coverage_binned --fasta=fixture/ref.fa --output=coverage_binned.h5 --format=hdf5 fixture/test.bam
